security:
    providers:
         default_provider:
            entity:
                class: AppBundle:Usuario
                property: username                
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: md5
            encode_as_base64: false
            iterations: 0            
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                 path: logout
                 target: /
                 invalidate_session: true
            provider: default_provider     
